name: WeChat Notify Job Runner

on:

  schedule:
    #每天18点31
    - cron: 31 8 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:

      - name: Initialization Values
        run: |
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
          sudo timedatectl set-timezone Asia/Shanghai

      - uses: actions/checkout@v6
      - name: Generate config
        run: |      
          sed -i "s/__KEY__/${{ secrets.WeChat_Key}}/g" config_wechat.py
        shell: bash 
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          pip-install: -r requirements.txt
      - run: python index_notifier.py
 
